<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
        Include="Fixtures\embedded-document.md"
        LogicalName="AzHST.Tests.EmbeddedDocument.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AzHST.Application\AzHST.Application.csproj" />
    <ProjectReference Include="..\..\src\AzHST.Infrastructure\AzHST.Infrastructure.csproj" />
  </ItemGroup>

</Project>