using System.Text;
using AzHST.Application.Models;
using AzHST.Application.Services;
using DocumentFormat.OpenXml.Packaging;
using A = DocumentFormat.OpenXml.Drawing;
using P = DocumentFormat.OpenXml.Presentation;

namespace AzHST.Infrastructure.Tests;

public sealed class OpenXmlPresentationBuilderTests : IDisposable
{
    private readonly string _testDirectory = Path.Combine(
        Path.GetTempPath(),
        "AzHST.Tests",
        Guid.NewGuid().ToString("N"));

    [Fact]
    public async Task BuildAsync_CreatesPresentationWithNativeSlidesAndAzureIcon()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var catalog = new FileAzureIconCatalog(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(catalog);
        var visualization = CreateVisualization();

        var artifact = await builder.BuildAsync(
            CreatePlan(),
            visualization,
            CreateTheme());

        Assert.Equal(5, artifact.SlideCount);
        Assert.Equal(
            Path.Combine(visualization.DirectoryPath, "presentation.pptx"),
            artifact.FilePath);
        Assert.True(File.Exists(artifact.FilePath));
        Assert.True(artifact.FileUri.IsFile);

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        Assert.Equal(5, presentationPart.SlideParts.Count());
        Assert.Single(
            presentationPart.SlideParts.SelectMany(slide => slide.ImageParts));

        var text = string.Join(
            " ",
            presentationPart.SlideParts
                .SelectMany(GetSlideText)
                .Select(item => item.Text));
        Assert.Contains("Azure Application Gateway", text);
        Assert.Contains("Validate before production", text);
        Assert.Contains("Resources / Sources", text);
        Assert.Contains("Application Gateway documentation", text);
        Assert.Contains(
            "https://learn.microsoft.com/azure/application-gateway/",
            text);
    }

    [Fact]
    public async Task BuildAsync_KeepsTraceabilityFooterOnlyOnTitleSlide()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));

        var artifact = await builder.BuildAsync(
            CreatePlan(),
            CreateVisualization(),
            CreateTheme());

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var slides = GetSlidesInOrder(presentationPart);
        var titleText = string.Join(
            " ",
            GetSlideText(slides[0]).Select(item => item.Text));
        Assert.Contains(
            "Generated by AzHST  |  0199abcd1234-application-gateway",
            titleText);

        foreach (var slide in slides.Skip(1))
        {
            var text = string.Join(
                " ",
                GetSlideText(slide).Select(item => item.Text));
            Assert.DoesNotContain(
                "0199abcd1234-application-gateway",
                text);
        }

        var resourcesText = string.Join(
            " ",
            GetSlideText(slides[^1]).Select(item => item.Text));
        Assert.Contains("Resources / Sources", resourcesText);
        Assert.Contains(
            "Official references and supporting documentation",
            resourcesText);
        Assert.Contains("2 REFERENCES", resourcesText);
        Assert.Contains("01", resourcesText);
        Assert.Contains("02", resourcesText);
        Assert.Contains("Application Gateway documentation", resourcesText);
        Assert.DoesNotContain("generated HTML", resourcesText);
    }

    [Fact]
    public async Task BuildAsync_RendersAllTenSources()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));
        var plan = CreatePlan();
        plan.Sources = Enumerable.Range(
                1,
                PresentationSourcePolicy.MaximumSourceCount)
            .Select(index => new PresentationSourcePlan
            {
                Title = $"Microsoft reference {index}",
                Url =
                    $"https://learn.microsoft.com/azure/reference-{index}",
            })
            .ToList();

        var artifact = await builder.BuildAsync(
            plan,
            CreateVisualization(),
            CreateTheme());

        using var document = PresentationDocument.Open(
            artifact.FilePath,
            false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var resourcesText = string.Join(
            " ",
            GetSlideText(GetSlidesInOrder(presentationPart)[^1])
                .Select(item => item.Text));

        Assert.Contains("10 REFERENCES", resourcesText);
        foreach (var source in plan.Sources)
        {
            Assert.Contains(source.Title, resourcesText);
            Assert.Contains(source.Url, resourcesText);
        }
    }

    [Fact]
    public async Task BuildAsync_ReplacesExistingPresentationAtomically()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));
        var visualization = CreateVisualization();

        var first = await builder.BuildAsync(
            CreatePlan(),
            visualization,
            CreateTheme());
        var firstLength = new FileInfo(first.FilePath).Length;
        var changedPlan = CreatePlan();
        changedPlan.Title = "Updated Azure Application Gateway";

        var second = await builder.BuildAsync(
            changedPlan,
            visualization,
            CreateTheme());

        Assert.Equal(first.FilePath, second.FilePath);
        Assert.NotEqual(0, new FileInfo(second.FilePath).Length);
        using var document = PresentationDocument.Open(second.FilePath, false);
        var text = string.Join(
            " ",
            document.PresentationPart!.SlideParts
                .SelectMany(GetSlideText)
                .Select(item => item.Text));
        Assert.Contains("Updated Azure Application Gateway", text);
        Assert.True(firstLength > 0);
    }

    [Fact]
    public async Task BuildAsync_UsesProfessionalLightTheme()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));

        var artifact = await builder.BuildAsync(
            CreatePlan(),
            CreateVisualization(),
            CreateTheme());

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var titleSlide = Assert.Single(
            presentationPart.SlideParts,
            slide => GetSlideText(slide)
                .Any(text => text.Text == "Request routing and protection"));
        var contentSlide = Assert.Single(
            presentationPart.SlideParts,
            slide => GetSlideText(slide)
                .Any(text => text.Text == "Executive overview"));

        Assert.Contains("F4F7FB", titleSlide.Slide!.OuterXml);
        Assert.Contains("0F2744", titleSlide.Slide.OuterXml);
        Assert.DoesNotContain("0B1020", titleSlide.Slide.OuterXml);
        Assert.Contains("F4F7FB", contentSlide.Slide!.OuterXml);
        Assert.Contains("0078D4", contentSlide.Slide.OuterXml);
    }

    [Fact]
    public async Task BuildAsync_AppliesConfiguredPaletteAndFonts()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));
        var defaultTheme = CreateTheme();
        var configuredTheme = defaultTheme with
        {
            Palette = defaultTheme.Palette with
            {
                Canvas = "#FAFBFC",
                Primary = "#123456",
            },
            Typography = defaultTheme.Typography with
            {
                FontFamily = "Arial",
                DisplayFontFamily = "Georgia",
            },
        };

        var artifact = await builder.BuildAsync(
            CreatePlan(),
            CreateVisualization(),
            configuredTheme);

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var slideXml = string.Join(
            Environment.NewLine,
            presentationPart.SlideParts.Select(slide => slide.Slide!.OuterXml));
        var themeXml = presentationPart.SlideMasterParts
            .Select(part => part.ThemePart?.Theme?.OuterXml)
            .First(xml => xml is not null);

        Assert.Contains("FAFBFC", slideXml);
        Assert.Contains("123456", slideXml);
        Assert.Contains("typeface=\"Arial\"", themeXml);
        Assert.Contains("typeface=\"Georgia\"", themeXml);
        Assert.Contains("typeface=\"Arial\"", slideXml);
        Assert.Contains("typeface=\"Georgia\"", slideXml);
    }

    [Fact]
    public async Task BuildAsync_ConnectsAdjacentDiagramNodesAtTheirEdges()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));

        var artifact = await builder.BuildAsync(
            CreatePlan(),
            CreateVisualization(),
            CreateTheme());

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var diagramSlide = Assert.Single(
            presentationPart.SlideParts,
            slide => GetSlideText(slide)
                .Any(text => text.Text == "Request flow"));
        var connectors = diagramSlide.Slide!
            .Descendants<P.ConnectionShape>()
            .ToArray();

        Assert.Equal(2, connectors.Length);
        Assert.All(
            connectors,
            connector =>
            {
                var transform = Assert.IsType<A.Transform2D>(
                    connector.ShapeProperties!.Transform2D);
                var extents = Assert.IsType<A.Extents>(transform.Extents);
                var outline = Assert.IsType<A.Outline>(
                    connector.ShapeProperties.GetFirstChild<A.Outline>());
                var headEnd = Assert.IsType<A.HeadEnd>(
                    outline.GetFirstChild<A.HeadEnd>());
                var tailEnd = Assert.IsType<A.TailEnd>(
                    outline.GetFirstChild<A.TailEnd>());

                Assert.InRange(extents.Cx!.Value, 1, 600_000);
                Assert.Equal(A.LineEndValues.None, headEnd.Type!.Value);
                Assert.Equal(A.LineEndValues.Triangle, tailEnd.Type!.Value);
            });
    }

    [Fact]
    public async Task BuildAsync_RoutesBranchingDiagramThroughGridGutters()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));

        var artifact = await builder.BuildAsync(
            CreateBranchingPlan(),
            CreateVisualization(),
            CreateTheme());

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var diagramSlide = Assert.Single(
            presentationPart.SlideParts,
            slide => GetSlideText(slide)
                .Any(text => text.Text == "Warm up, then swap"));
        var connectors = diagramSlide.Slide!
            .Descendants<P.ConnectionShape>()
            .ToArray();

        Assert.Equal(8, connectors.Length);
        Assert.Equal(
            4,
            connectors.Count(
                connector => connector.ShapeProperties!
                    .GetFirstChild<A.Outline>()!
                    .GetFirstChild<A.TailEnd>()!
                    .Type?.Value == A.LineEndValues.Triangle));
        Assert.Contains(
            connectors,
            connector =>
            {
                var extents = connector.ShapeProperties!
                    .Transform2D!
                    .Extents!;
                return extents.Cx?.Value > 2_000_000
                    && extents.Cy?.Value == 1;
            });

        var slideText = GetSlideText(diagramSlide)
            .Select(text => text.Text)
            .ToArray();
        Assert.DoesNotContain("Production hostname stays fixed", slideText);
        Assert.DoesNotContain("Staging hostname stays fixed", slideText);

        var productionLabel = Assert.Single(
            diagramSlide.Slide.Descendants<P.Shape>(),
            shape => GetShapeText(shape) == "Production · Green");
        var stagingLabel = Assert.Single(
            diagramSlide.Slide.Descendants<P.Shape>(),
            shape => GetShapeText(shape) == "Staging · Blue");
        Assert.True(
            productionLabel.ShapeProperties!.Transform2D!.Offset!.X?.Value
                > 2_400_000);
        Assert.True(
            stagingLabel.ShapeProperties!.Transform2D!.Offset!.X?.Value
                > 6_000_000);

        Assert.DoesNotContain(
            diagramSlide.Slide.Descendants<P.Shape>(),
            shape => GetShapeText(shape).Contains(
                "0199abcd1234-application-gateway",
                StringComparison.Ordinal));
        Assert.NotEmpty(diagramSlide.Slide.Descendants<A.NormalAutoFit>());
    }

    [Fact]
    public async Task BuildAsync_RendersVisualCardsAndNumberedCardsAsNativeShapes()
    {
        var iconDirectory = Path.Combine(_testDirectory, "icons");
        CreateIcon(iconDirectory);
        var builder = new OpenXmlPresentationBuilder(
            new FileAzureIconCatalog(iconDirectory));

        var artifact = await builder.BuildAsync(
            CreatePlan(),
            CreateVisualization(),
            CreateTheme());

        using var document = PresentationDocument.Open(artifact.FilePath, false);
        var presentationPart = Assert.IsType<PresentationPart>(
            document.PresentationPart);
        var cardsSlide = Assert.Single(
            presentationPart.SlideParts,
            slide => GetSlideText(slide)
                .Any(text => text.Text == "Executive overview"));
        var summarySlide = Assert.Single(
            presentationPart.SlideParts,
            slide => GetSlideText(slide)
                .Any(text => text.Text == "Validate before production"));

        var cardsShapes = cardsSlide.Slide!.Descendants<P.Shape>().ToArray();
        Assert.Single(
            cardsShapes,
            shape => GetShapeText(shape) == "Request routing");
        Assert.Single(
            cardsShapes,
            shape => GetShapeText(shape) == "Web protection");
        Assert.Single(
            cardsShapes,
            shape => GetShapeText(shape) == "How requests are processed");
        Assert.Contains(
            cardsShapes,
            shape =>
            {
                var text = GetShapeText(shape);
                return text.Contains(
                        "Route and protect traffic",
                        StringComparison.Ordinal)
                    && text.Contains(
                        "Application Gateway is a regional layer 7 load balancer.",
                        StringComparison.Ordinal)
                    && text.Contains(
                        "Important: frontend and backend TLS are separate.",
                        StringComparison.Ordinal);
            });
        Assert.Contains("009FDA", cardsSlide.Slide.OuterXml);
        Assert.Contains("14B8A6", cardsSlide.Slide.OuterXml);
        Assert.DoesNotContain(
            presentationPart.SlideParts
                .SelectMany(slide => slide.Slide!.Descendants<P.Shape>()),
            shape =>
            {
                var extents = shape.ShapeProperties?.Transform2D?.Extents;
                return extents?.Cy?.Value == 64_008
                    && extents.Cx?.Value > 900_000;
            });

        var summaryShapes = summarySlide.Slide!.Descendants<P.Shape>().ToArray();
        const string firstPoint = "Check regional and SKU availability.";
        const string secondPoint =
            "Validate quotas, pricing, and WAF policy behavior.";
        Assert.Single(
            summaryShapes,
            shape => GetShapeText(shape) == firstPoint);
        Assert.Single(
            summaryShapes,
            shape => GetShapeText(shape) == secondPoint);
        Assert.DoesNotContain(
            summaryShapes,
            shape =>
            {
                var text = GetShapeText(shape);
                return text.Contains(firstPoint, StringComparison.Ordinal)
                && text.Contains(secondPoint, StringComparison.Ordinal);
            });
    }

    public void Dispose()
    {
        if (Directory.Exists(_testDirectory))
        {
            Directory.Delete(_testDirectory, recursive: true);
        }
    }

    private VisualizationArtifact CreateVisualization()
    {
        var directory = Path.Combine(
            _testDirectory,
            "generated",
            "0199abcd1234-application-gateway");
        Directory.CreateDirectory(directory);
        var htmlPath = Path.Combine(directory, "index.html");
        File.WriteAllText(htmlPath, "<!doctype html><html></html>");

        return new VisualizationArtifact(
            "0199abcd1234-application-gateway",
            directory,
            htmlPath,
            new Uri(htmlPath, UriKind.Absolute));
    }

    private static PresentationPlan CreatePlan()
    {
        return new PresentationPlan
        {
            Title = "Azure Application Gateway",
            Subtitle = "Request routing and protection",
            Sources =
            [
                new PresentationSourcePlan
                {
                    Title = "Application Gateway documentation",
                    Url =
                        "https://learn.microsoft.com/azure/application-gateway/",
                },
                new PresentationSourcePlan
                {
                    Title = "Application Gateway architecture guidance",
                    Url =
                        "https://learn.microsoft.com/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app",
                },
            ],
            Slides =
            [
                new PresentationSlidePlan
                {
                    Kind = "cards",
                    SectionTitle = "How requests are processed",
                    Title = "Executive overview",
                    Subtitle = "Route and protect traffic",
                    Summary = "Application Gateway is a regional layer 7 load balancer.",
                    Callout =
                        "Important: frontend and backend TLS are separate.",
                    Nodes =
                    [
                        new PresentationNodePlan
                        {
                            Id = "routing",
                            Label = "Request routing",
                            Detail = "Evaluates listeners and routing rules.",
                            Tone = "accent",
                        },
                        new PresentationNodePlan
                        {
                            Id = "waf",
                            Label = "Web protection",
                            Detail = "Applies Web Application Firewall policies.",
                            Tone = "success",
                        },
                    ],
                    Sources = ["Microsoft Learn"],
                },
                new PresentationSlidePlan
                {
                    Kind = "diagram",
                    Title = "Request flow",
                    Summary = "A request passes through the gateway before reaching the backend.",
                    Nodes =
                    [
                        new PresentationNodePlan
                        {
                            Id = "client",
                            Label = "Client",
                            Detail = "Sends an HTTPS request.",
                            Tone = "neutral",
                        },
                        new PresentationNodePlan
                        {
                            Id = "gateway",
                            Label = "Azure Application Gateway",
                            Detail = "Evaluates WAF and routing rules.",
                            IconKey = "networking/10076-application-gateways",
                            Tone = "primary",
                        },
                        new PresentationNodePlan
                        {
                            Id = "backend",
                            Label = "Backend pool",
                            Detail = "Receives healthy routed traffic.",
                            Tone = "success",
                        },
                    ],
                    Connections =
                    [
                        new PresentationConnectionPlan
                        {
                            From = "client",
                            To = "gateway",
                            Label = "HTTPS",
                        },
                        new PresentationConnectionPlan
                        {
                            From = "gateway",
                            To = "backend",
                            Label = "HTTP(S)",
                        },
                    ],
                    Sources = ["Azure Architecture Center"],
                },
                new PresentationSlidePlan
                {
                    Kind = "summary",
                    Title = "Validate before production",
                    Summary = "Confirm design assumptions against current Azure guidance.",
                    Bullets =
                    [
                        "Check regional and SKU availability.",
                        "Validate quotas, pricing, and WAF policy behavior.",
                    ],
                    Sources = ["Microsoft Learn"],
                },
            ],
        };
    }

    private static PresentationPlan CreateBranchingPlan()
    {
        return new PresentationPlan
        {
            Title = "Azure App Service blue-green deployment",
            Subtitle = "Deployment slots and rollback",
            Slides =
            [
                new PresentationSlidePlan
                {
                    Kind = "diagram",
                    Title = "Warm up, then swap",
                    Summary = "Swap verified slot contents while hostnames remain stable.",
                    Nodes =
                    [
                        new PresentationNodePlan
                        {
                            Id = "staging-green",
                            Label = "Staging · Green",
                            Detail = "The verified candidate is ready in staging.",
                            Tone = "success",
                        },
                        new PresentationNodePlan
                        {
                            Id = "warm-up",
                            Label = "Warm up target slot",
                            Detail = "Prepare the target slot before cutover.",
                            Tone = "neutral",
                        },
                        new PresentationNodePlan
                        {
                            Id = "swap",
                            Label = "Swap slot contents",
                            Detail = "Exchange slot content and configuration.",
                            Tone = "primary",
                        },
                        new PresentationNodePlan
                        {
                            Id = "production-green",
                            Label = "Production · Green",
                            Detail = "Green serves the production hostname.",
                            Tone = "success",
                        },
                        new PresentationNodePlan
                        {
                            Id = "staging-blue",
                            Label = "Staging · Blue",
                            Detail = "Blue remains available in staging.",
                            Tone = "neutral",
                        },
                    ],
                    Connections =
                    [
                        new PresentationConnectionPlan
                        {
                            From = "staging-green",
                            To = "warm-up",
                            Label = "Prepare candidate",
                        },
                        new PresentationConnectionPlan
                        {
                            From = "warm-up",
                            To = "swap",
                            Label = "Ready for cutover",
                        },
                        new PresentationConnectionPlan
                        {
                            From = "swap",
                            To = "production-green",
                            Label = "Production hostname stays fixed",
                        },
                        new PresentationConnectionPlan
                        {
                            From = "swap",
                            To = "staging-blue",
                            Label = "Staging hostname stays fixed",
                        },
                    ],
                    Sources =
                    [
                        "Azure App Service deployment slots",
                        "Azure App Service swap operation",
                        "Azure App Service Health check",
                    ],
                },
            ],
        };
    }

    private static PresentationThemeDefinition CreateTheme()
    {
        return new PresentationThemeDefinition
        {
            SchemaVersion = 1,
            Id = "professional-light",
            DisplayName = "Professional Light",
            Palette = new PresentationThemePalette
            {
                Canvas = "#F4F7FB",
                Surface = "#FFFFFF",
                SummarySurface = "#EAF4FC",
                Title = "#0F2744",
                Text = "#172033",
                TextMuted = "#526176",
                Border = "#CBD6E2",
                Primary = "#0078D4",
                Accent = "#009FDA",
                IconTile = "#EAF4FC",
                Success = "#14B8A6",
                Warning = "#F59E0B",
                Comparison = "#8B5CF6",
                Danger = "#EF4444",
                Hyperlink = "#0563C1",
                FollowedHyperlink = "#954F72",
            },
            Typography = new PresentationThemeTypography
            {
                FontFamily = "Aptos",
                DisplayFontFamily = "Aptos Display",
                TitleSizePoints = 32,
                SubtitleSizePoints = 17,
                SlideTitleSizePoints = 20,
                SummarySizePoints = 15,
                BodySizePoints = 17,
                NodeLabelSizePoints = 12,
                NodeDetailSizePoints = 10,
                ConnectionLabelSizePoints = 8,
                FooterSizePoints = 7,
            },
            Appearance = new PresentationThemeAppearance
            {
                RoundedCards = true,
                ShowHeaderRule = true,
                IconTreatment = PresentationIconTreatment.LightTile,
            },
        };
    }

    private static void CreateIcon(string iconDirectory)
    {
        var directory = Path.Combine(iconDirectory, "networking");
        Directory.CreateDirectory(directory);
        File.WriteAllText(
            Path.Combine(
                directory,
                "10076-icon-service-Application-Gateways.svg"),
            """
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
              <path d="M1 1h16v16H1z" fill="#0078d4" />
            </svg>
            """,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    private static IReadOnlyList<SlidePart> GetSlidesInOrder(
        PresentationPart presentationPart)
    {
        var presentation = presentationPart.Presentation
            ?? throw new InvalidOperationException(
                "Test presentation is missing.");
        var slideIds = presentation.SlideIdList
            ?? throw new InvalidOperationException(
                "Test presentation has no slides.");
        return slideIds
            .Elements<P.SlideId>()
            .Select(slideId => Assert.IsType<SlidePart>(
                presentationPart.GetPartById(
                    slideId.RelationshipId?.Value
                        ?? throw new InvalidOperationException(
                            "Test slide has no relationship ID."))))
            .ToArray();
    }

    private static IEnumerable<DocumentFormat.OpenXml.Drawing.Text> GetSlideText(
        SlidePart slidePart)
    {
        return (slidePart.Slide
                ?? throw new InvalidOperationException("Test slide is missing."))
            .Descendants<DocumentFormat.OpenXml.Drawing.Text>();
    }

    private static string GetShapeText(P.Shape shape)
    {
        return string.Join(
            " ",
            shape.Descendants<DocumentFormat.OpenXml.Drawing.Text>()
                .Select(text => text.Text));
    }
}
