<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AzHST.Application\AzHST.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsRidAgnostic>false</IsRidAgnostic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="GitHub.Copilot.SDK" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
